name: Tania Paiva
description: "My personal site with stuff I enjoy and learn everyday."
baseurl:
url: https://taniadaniela.github.io
download:
social:
  github: taniadaniela
  email: taniadaniela1803@mail.com
  facebook:
  twitter:
  instagram: taniadaniela18
  tumblr:
author:
  name: Tania Paiva
  bio: "Software engineer working remotely with JS, Ruby and Elixir."
  email: taniadaniela1803@mail.com
  image: /assets/images/author.jpg
  github: taniadaniela18
  facebook:
  twitter:
  instagram:
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
