# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://taniadaniela.github.io/'
baseurl: ''
title: 'Tania Paiva'
description: 'oh, is a website.. and is mine.'
permalink: pretty
logo: "https://s.gravatar.com/avatar/ccb1fa9efb0178eddc5db29e3bb625b3?s=80"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
